### ISSUE TITLE
Support decoding indefinite length encodings

### ISSUE THREAD

**Issue by glguy** [BurntSushi/rust-cbor#12]
I'm interested in using this crate to decode CBOR structures that happen to use indefinite length encodings. I've locally patched the code to support this locally. I'd be willing to submit a pull-request soon.

I'm interested to know what you plans are for supporting indefinite lengths in general. For my use-case it is sufficient for me to add support to read_array, read_map, read_bytes, and read_string in decoder.rs. Are there some other considerations?

**Comment by BurntSushi** [comment]
@glguy Ah that's awesome! I'll be honest, I haven't given much thought to it, and I'm not sure how much maintenance I'll be able to do on this crate. I kind of feel like the best thing to do is to switch to a CBOR crate that supports serde.

With that said, if your PR is relatively small and well tested, then I think I could probably accept it!

**Comment by glguy** [comment]
Do you happen to know of such a CBOR crate that supports serde that I should be looking at?

**Comment by BurntSushi** [comment]
Ah hmm, I guess the one I had in mind was here https://github.com/pyfisch/cbor, but that one also appears unmaintained.

**Comment by glguy** [comment]
What versions of Rust are you trying to maintain compatibility with? Is it acceptable to update to features in the stable release of Rust like the `?` syntax for `try!`?

**Comment by BurntSushi** [comment]
Yeah that's fine. I can bump the minimum Rust version to I think at least 1.17 (two versions behind current stable).
