### ISSUE TITLE
non-string keys in maps not supported

### ISSUE THREAD

**Issue by mozkeeler** [BurntSushi/rust-cbor#13]
Unless I'm misunderstanding, rust-cbor doesn't support non-string keys in CBOR maps. From my reading of the rfc, types other than strings may be used as keys in maps.

For instance, the hex bytes `a10126` should decode as a map with one entry: a key of an unsigned integer of value 1 mapping to a value of the negative integer -7. Right now the decoder throws a TypeMismatch error expecting a Unicode string.

**Comment by BurntSushi** [comment]
Yes, I believe that is correct. I think the CBOR RFC says that some
implementations can choose to restrict keys to Unicode strings.

I would be okay with fixing that, but probably won't do it myself.
