### ISSUE TITLE
Decouple dependencies

### ISSUE THREAD

**Issue by hkcorac** [BurntSushi/rust-cbor#16]
Hi,

May I ask if you could decouple dependencies? For a basic, simple and concise implementation, I think it would be great if there are no dependencies.

For more features, maybe you can make a separate crate...

Thank you,

**Comment by BurntSushi** [comment]
Sorry, but I don't understand what you're asking for. Issuing directives
based on abstract principles is unlikely to get you anywhere. Instead,
please describe the problem you want to solve.

With that said, I don't see myself doing anything with this crate. If you
have a different vision for CBOR in Rust, then I would encourage you to
build it.

**Comment by BurntSushi** [comment]
@hkcorac Thanks for clarifying. Generally, asking other people to "rebuild" entire libraries without doing any kind of research yourself about what exactly that would entail is not appreciated. Please don't do it. Instead, focus on the problem that you're trying to solve.

**Comment by hkcorac** [comment]
@BurntSushi 

Thanks. I really didn't mean to ask you to do anything. That's why I used a _"May I ask..."_ question. I did mean just to suggest a change.

From the specification here: <https://tools.ietf.org/html/rfc7049>, at point 1.1.2, I _thought_ the code would be short. That was my fault. So I'm sorry.

**Comment by hkcorac** [comment]
I'm sorry I accidentally clicked _"Reopen"_ button.
