### ISSUE TITLE
De/Serialize enums with arguments as integer

### ISSUE THREAD

**Issue by nifker** [BurntSushi/rust-cbor#18]
Would it be possible to have an enum like Foo(String) or Bar(structA) but the key(Foo or Bar) would be an integer if I use e.g. #[repr(u8)]?

**Comment by nifker** [comment]
Or is this similiar to https://github.com/BurntSushi/rust-cbor/issues/13 ?

**Comment by BurntSushi** [comment]
I don't think I understand your question. In any case, this project is not maintained. I've added an [explicit notice](https://github.com/BurntSushi/rust-cbor/commit/5335bdb0b9c7c5be371ba99011b5fdda8f02b1ca) saying as much.
